[versions]
kotlin="2.0.0"
maven-publish-version="0.29.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPlugin = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish-version" }
